services:
  fleet-routing:
    build: .
    env_file: .env
    volumes:
      - "./google_service_account_key.json:/usr/src/app/google_service_account_key.json"
    ports:
      - 8080:8080
      - 443:443
